import { createRouter, createWebHashHistory } from 'vue-router'

const router = createRouter({
  history: createWebHashHistory(),
  routes: [
    { path: '/', component: () => import('./views/HomeView.vue') },

    // EUI Components (existing demos, prefixed with /eui)
    { path: '/eui', component: () => import('./views/EuiOverview.vue') },
    { path: '/eui/integration', component: () => import('./views/EuiIntegrationDoc.vue') },
    { path: '/eui/button', component: () => import('./views/ButtonDemo.vue') },
    { path: '/eui/input', component: () => import('./views/InputDemo.vue') },
    { path: '/eui/select', component: () => import('./views/SelectDemo.vue') },
    { path: '/eui/checkbox', component: () => import('./views/CheckboxDemo.vue') },
    { path: '/eui/radio', component: () => import('./views/RadioDemo.vue') },
    { path: '/eui/switch', component: () => import('./views/SwitchDemo.vue') },
    { path: '/eui/form', component: () => import('./views/FormDemo.vue') },
    { path: '/eui/table', component: () => import('./views/TableDemo.vue') },
    { path: '/eui/dialog', component: () => import('./views/DialogDemo.vue') },
    { path: '/eui/drawer', component: () => import('./views/DrawerDemo.vue') },
    { path: '/eui/toast', component: () => import('./views/ToastDemo.vue') },
    { path: '/eui/tabs', component: () => import('./views/TabsDemo.vue') },
    { path: '/eui/menu', component: () => import('./views/MenuDemo.vue') },
    { path: '/eui/card', component: () => import('./views/CardDemo.vue') },
    { path: '/eui/alert', component: () => import('./views/AlertDemo.vue') },
    { path: '/eui/badge', component: () => import('./views/BadgeDemo.vue') },
    { path: '/eui/tooltip', component: () => import('./views/TooltipDemo.vue') },
    { path: '/eui/popover', component: () => import('./views/PopoverDemo.vue') },
    { path: '/eui/dropdown', component: () => import('./views/DropdownDemo.vue') },
    { path: '/eui/pagination', component: () => import('./views/PaginationDemo.vue') },
    { path: '/eui/breadcrumb', component: () => import('./views/BreadcrumbDemo.vue') },
    { path: '/eui/tags-input', component: () => import('./views/TagsInputDemo.vue') },
    { path: '/eui/date-picker', component: () => import('./views/DatePickerDemo.vue') },
    { path: '/eui/time-picker', component: () => import('./views/TimePickerDemo.vue') },
    { path: '/eui/tree', component: () => import('./views/TreeDemo.vue') },
    { path: '/eui/upload', component: () => import('./views/UploadDemo.vue') },
    { path: '/eui/progress', component: () => import('./views/ProgressDemo.vue') },
    { path: '/eui/accordion', component: () => import('./views/AccordionDemo.vue') },
    { path: '/eui/stepper', component: () => import('./views/StepperDemo.vue') },
    { path: '/eui/carousel', component: () => import('./views/CarouselDemo.vue') },
    { path: '/eui/avatar', component: () => import('./views/AvatarDemo.vue') },
    { path: '/eui/skeleton', component: () => import('./views/SkeletonDemo.vue') },
    { path: '/eui/slider', component: () => import('./views/SliderDemo.vue') },
    { path: '/eui/rate', component: () => import('./views/RateDemo.vue') },
    { path: '/eui/transfer', component: () => import('./views/TransferDemo.vue') },
    { path: '/eui/descriptions', component: () => import('./views/DescriptionsDemo.vue') },
    { path: '/eui/timeline', component: () => import('./views/TimelineDemo.vue') },
    { path: '/eui/statistic', component: () => import('./views/StatisticDemo.vue') },
    { path: '/eui/typography', component: () => import('./views/TypographyDemo.vue') },
    { path: '/eui/kbd', component: () => import('./views/KbdDemo.vue') },
    { path: '/eui/separator', component: () => import('./views/SeparatorDemo.vue') },
    { path: '/eui/spinner', component: () => import('./views/SpinnerDemo.vue') },
    { path: '/eui/empty', component: () => import('./views/EmptyDemo.vue') },
    { path: '/eui/label', component: () => import('./views/LabelDemo.vue') },
    { path: '/eui/aspect-ratio', component: () => import('./views/AspectRatioDemo.vue') },
    { path: '/eui/form-dialog', component: () => import('./views/FormDialogDemo.vue') },
    { path: '/eui/confirm-dialog', component: () => import('./views/ConfirmDialogDemo.vue') },
    { path: '/eui/data-page', component: () => import('./views/DataPageDemo.vue') },
    { path: '/eui/alert-dialog', component: () => import('./views/AlertDialogDemo.vue') },
    { path: '/eui/sheet', component: () => import('./views/SheetDemo.vue') },
    { path: '/eui/hover-card', component: () => import('./views/HoverCardDemo.vue') },
    { path: '/eui/context-menu', component: () => import('./views/ContextMenuDemo.vue') },
    { path: '/eui/collapsible', component: () => import('./views/CollapsibleDemo.vue') },
    { path: '/eui/scroll-area', component: () => import('./views/ScrollAreaDemo.vue') },
    { path: '/eui/image', component: () => import('./views/ImageDemo.vue') },
    { path: '/eui/calendar', component: () => import('./views/CalendarDemo.vue') },
    { path: '/eui/range-calendar', component: () => import('./views/RangeCalendarDemo.vue') },
    { path: '/eui/tree-select', component: () => import('./views/TreeSelectDemo.vue') },
    { path: '/eui/virtual-table', component: () => import('./views/VirtualTableDemo.vue') },
    { path: '/eui/admin-layout', component: () => import('./views/AdminLayoutDemo.vue') },
    { path: '/eui/ai-chat', component: () => import('./views/AIChatDemo.vue') },
    { path: '/eui/timetable-grid', component: () => import('./views/TimetableGridDemo.vue') },
    { path: '/eui/chart', component: () => import('./views/ChartDemo.vue') },
    { path: '/eui/menubar', component: () => import('./views/MenubarDemo.vue') },
    { path: '/eui/navigation-menu', component: () => import('./views/NavigationMenuDemo.vue') },
    { path: '/eui/toggle', component: () => import('./views/ToggleDemo.vue') },
    { path: '/eui/toggle-group', component: () => import('./views/ToggleGroupDemo.vue') },
    { path: '/eui/button-group', component: () => import('./views/ButtonGroupDemo.vue') },
    { path: '/eui/input-group', component: () => import('./views/InputGroupDemo.vue') },
    { path: '/eui/resizable', component: () => import('./views/ResizableDemo.vue') },
    { path: '/eui/infinite-scroll', component: () => import('./views/InfiniteScrollDemo.vue') },
    { path: '/eui/affix', component: () => import('./views/AffixDemo.vue') },
    { path: '/eui/watermark', component: () => import('./views/WatermarkDemo.vue') },
    { path: '/eui/mention', component: () => import('./views/MentionDemo.vue') },
    { path: '/eui/textarea', component: () => import('./views/TextareaDemo.vue') },
    { path: '/eui/autocomplete', component: () => import('./views/AutocompleteDemo.vue') },
    { path: '/eui/cascader', component: () => import('./views/CascaderDemo.vue') },
    { path: '/eui/color-picker', component: () => import('./views/ColorPickerDemo.vue') },
    { path: '/eui/combobox', component: () => import('./views/ComboboxDemo.vue') },
    { path: '/eui/input-otp', component: () => import('./views/InputOtpDemo.vue') },
    { path: '/eui/native-select', component: () => import('./views/NativeSelectDemo.vue') },
    { path: '/eui/number-field', component: () => import('./views/NumberFieldDemo.vue') },
    { path: '/eui/pin-input', component: () => import('./views/PinInputDemo.vue') },
    { path: '/eui/command', component: () => import('./views/CommandDemo.vue') },
    { path: '/eui/config-provider', component: () => import('./views/ConfigProviderDemo.vue') },
    { path: '/eui/field', component: () => import('./views/FieldDemo.vue') },
    { path: '/eui/item', component: () => import('./views/ItemDemo.vue') },

    // Blocks
    { path: '/eui/blocks/login-01', component: () => import('./views/blocks/Login01.vue') },
    { path: '/eui/blocks/login-02', component: () => import('./views/blocks/Login02.vue') },
    { path: '/eui/blocks/login-04', component: () => import('./views/blocks/Login04.vue') },
    { path: '/eui/blocks/otp-01', component: () => import('./views/blocks/Otp01.vue') },

    // EKit (Core)
    { path: '/ekit', component: () => import('./views/core/CoreOverview.vue') },
    { path: '/ekit/request', component: () => import('./views/core/RequestDoc.vue') },
    { path: '/ekit/storage', component: () => import('./views/core/StorageDoc.vue') },
    { path: '/ekit/validators', component: () => import('./views/core/ValidatorsDoc.vue') },
    { path: '/ekit/date', component: () => import('./views/core/DateDoc.vue') },
    { path: '/ekit/hooks', component: () => import('./views/core/HooksDoc.vue') },

    // EApi (Backend)
    { path: '/eapi', component: () => import('./views/backend/BackendOverview.vue') },
    { path: '/eapi/config', component: () => import('./views/backend/ConfigDoc.vue') },
    { path: '/eapi/database', component: () => import('./views/backend/DatabaseDoc.vue') },
    { path: '/eapi/security', component: () => import('./views/backend/SecurityDoc.vue') },
    { path: '/eapi/exceptions', component: () => import('./views/backend/ExceptionsDoc.vue') },
    { path: '/eapi/response', component: () => import('./views/backend/ResponseDoc.vue') },
    { path: '/eapi/pagination', component: () => import('./views/backend/PaginationDoc.vue') },
    { path: '/eapi/cache', component: () => import('./views/backend/CacheDoc.vue') },
    { path: '/eapi/dependencies', component: () => import('./views/backend/DependenciesDoc.vue') },
    { path: '/eapi/logger', component: () => import('./views/backend/LoggerDoc.vue') },
    { path: '/eapi/health', component: () => import('./views/backend/HealthDoc.vue') },
    { path: '/eapi/masking', component: () => import('./views/backend/MaskingDoc.vue') },
    { path: '/eapi/dt', component: () => import('./views/backend/DtDoc.vue') },
    { path: '/eapi/tasks', component: () => import('./views/backend/TasksDoc.vue') },
    { path: '/eapi/email', component: () => import('./views/backend/EmailProviderDoc.vue') },

    // @dwydev/admin-kit 全屏预览（meta.bare 隐藏门户 chrome）
    {
      path: '/admin',
      component: () => import('./views/admin/AdminDemoHost.vue'),
      meta: { bare: true },
      children: [
        { path: '', redirect: '/admin/dashboard' },
        {
          path: 'dashboard',
          component: () => import('./views/admin/AdminDemoPage.vue'),
          meta: {
            title: '数据概览',
            description: '默认首页 defaultPath=/admin/dashboard，登录后可直接进入。',
          },
        },
        {
          path: 'ops/users',
          component: () => import('./views/admin/AdminDemoPage.vue'),
          meta: {
            title: '用户列表',
            description: '子菜单示例：运营 → 用户列表。',
            menuKey: '/admin/ops/users',
            breadcrumb: [
              { label: '运营' },
              { label: '用户列表' },
            ],
          },
        },
        {
          path: 'ops/plans',
          component: () => import('./views/admin/AdminDemoPage.vue'),
          meta: {
            title: '套餐管理',
            description: '子菜单示例：运营 → 套餐管理。',
            menuKey: '/admin/ops/plans',
            breadcrumb: [
              { label: '运营' },
              { label: '套餐管理' },
            ],
          },
        },
        {
          path: 'quota',
          component: () => import('./views/admin/AdminDemoPage.vue'),
          meta: { title: '用量统计', description: '一级菜单示例。' },
        },
        {
          path: 'keys',
          component: () => import('./views/admin/AdminDemoPage.vue'),
          meta: { title: 'API Key', description: '一级菜单示例。' },
        },
        {
          path: 'settings',
          component: () => import('./views/admin/AdminDemoPage.vue'),
          meta: {
            title: '个人设置',
            description: '用户下拉「个人中心」默认跳转本页。',
          },
        },
      ],
    },

    // CLI
    { path: '/cli', component: () => import('./views/cli/CliOverview.vue') },
    { path: '/cli/create-dwy', component: () => import('./views/cli/CreateDwyDoc.vue') },

    // Claude Code
    { path: '/claude', component: () => import('./views/claude/ClaudeOverview.vue') },
    { path: '/claude/skills/:name', component: () => import('./views/claude/SkillDoc.vue') },
    { path: '/claude/rules/:name', component: () => import('./views/claude/RuleDoc.vue') },
    { path: '/claude/hooks/:name', component: () => import('./views/claude/HookDoc.vue') },
    { path: '/claude/settings', component: () => import('./views/claude/SettingsDoc.vue') },
  ],
})

export default router
